### ISSUE TITLE
Ansicolor error after 0.5.4

### ISSUE THREAD

**Issue by loladinha96** [flutter-webrtc/dart-sip-ua#354] opened 2023-03-16 13:23 UTC
# Summary
Basically after upgrading to version 0.5.4 i started getting an error with AnsiColor trying to access this object and drowing an error gradle doesn't even compile, the solution is very simple just add some brackets and it's done.

# Solution
Line 133 looger.dart `return '$this$msg$ansiDefault';   ->  return '${this}$msg$ansiDefault';`

**Comment by Perondas** [comment] 2023-03-20 13:56
This is a duplicate of #347
This is an issue with flutter. The fix is to update it, preferably to the latest version.

**Closed by Perondas** 2023-03-20 13:56 UTC
